language: python
python:
  - '3.6'
  - '3.7-dev'
install:
  - python setup.py -q install
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
script:
  - pytest --cov=spooti/
after_success:
  - coveralls